In [3]:
import yfinance as yf
import pandas as pd
import os
os.chdir('C:/Users/clair/PolyNex/PPP/PPP_Repilcation/PPP_Repilcation/Data')

In [93]:
ticker_list = pd.read_csv('ticker_list.csv')    
ticker_list = list(ticker_list.iloc[:,0])

In [94]:
class GetStockData():
    def __init__(self,ticker_list):
        self.ticker_list = ticker_list
    
    def __ticker_tostr__(self):
        '''
        convert ticker_list to a long string
        '''
        stop= ' '
        ticker_str = stop.join(self.ticker_list)
        return ticker_str
    
    def download_price(self,period='max',interval ='1d'):
        ticker_str = self.__ticker_tostr__()
        df = yf.download(ticker_list,period =period,interval=interval,group_by='ticker')
        return df
    
    def download_stock_info(self):
        pass
    
    def download_accounting(self):
        pass
    
    def download_balance_sheet(self):
        pass
    
    def download_cash_flow(self):
        pass
    
    def download_earnings(self):
        pass

In [95]:
obj = GetStockData(ticker_list)

In [97]:
df = obj.download_price()

[                       0%                       ]

Exception in thread Thread-132:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('603880.SZ', 'No data found, symbol may be delisted')

Exception in thread Thread-131:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('600587.SZ', 'No data found, symbol may be delisted')

Exception in thread Thread-135:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('688016.SZ', 'No data found, symbol may be delisted')

Exception in thread Thread-134:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('603309.SZ', 'No data found, symbol may be delisted')

Exception in thread Thread-136:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('688029.SZ', 'No data found, symbol may be delisted')

[**                     5%                       ]  4 of 86 downloaded

Exception in thread Thread-141:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('603108.SZ', 'No data found, symbol may be delisted')

[****                   9%                       ]  8 of 86 downloaded

Exception in thread Thread-145:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('688310.SZ', 'No data found, symbol may be delisted')

Exception in thread Thread-150:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('600767.SZ', 'No data found, symbol may be delisted')

[*******               14%                       ]  12 of 86 downloaded

Exception in thread Thread-151:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('603882.SZ', 'No data found, symbol may be delisted')

[********              16%                       ]  14 of 86 downloaded

Exception in thread Thread-154:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('600529.SZ', 'No data found, symbol may be delisted')

Exception in thread Thread-156:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('600721.SZ', 'No data found, symbol may be delisted')

Exception in thread Thread-159:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('600055.SZ', 'No data found, symbol may be delisted')

[*********             19%                       ]  16 of 86 downloaded

Exception in thread Thread-160:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('688068.SZ', 'No data found, symbol may be delisted')

[***********           22%                       ]  19 of 86 downloaded

Exception in thread Thread-163:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('603658.SZ', 'No data found, symbol may be delisted')

Exception in thread Thread-165:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('600896.SZ', 'No data found, symbol may be delisted')

[****************      33%                       ]  28 of 86 downloaded

Exception in thread Thread-173:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('688108.SZ', 'No data found, symbol may be delisted')

[********************* 43%                       ]  37 of 86 downloaded

Exception in thread Thread-183:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('603387.SZ', 'No data found, symbol may be delisted')

Exception in thread Thread-184:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('603127.SZ', 'No data found, symbol may be delisted')

[**********************45%                       ]  39 of 86 downloaded

Exception in thread Thread-190:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('688389.SZ', 'No data found, symbol may be delisted')

Exception in thread Thread-192:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('688358.SZ', 'No data found, symbol may be delisted')

[**********************51%                       ]  44 of 86 downloaded

Exception in thread Thread-195:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('688139.SZ', 'No data found, symbol may be delisted')

Exception in thread Thread-197:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('688202.SZ', 'No data found, symbol may be delisted')

[**********************55%*                      ]  47 of 86 downloaded

Exception in thread Thread-199:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('688366.SZ', 'No data found, symbol may be delisted')

Exception in thread Thread-200:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('603976.SZ', 'No data found, symbol may be delisted')

Exception in thread Thread-202:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('603367.SZ', 'No data found, symbol may be delisted')

Exception in thread Thread-204:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('603987.SZ', 'No data found, symbol may be delisted')

Exception in thread Thread-205:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('603259.SZ', 'No data found, symbol may be delisted')

Exception in thread Thread-206:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('600763.SZ', 'No data found, symbol may be delisted')

[**********************57%**                     ]  49 of 86 downloaded

Exception in thread Thread-210:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Anaconda3\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 470, in _download_one_threaded
    period, interval, prepost, proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 483, in _download_one
    proxy=proxy)
  File "C:\Anaconda3\lib\site-packages\yfinance\__init__.py", line 304, in history
    raise ValueError(self.ticker, err_msg)
ValueError: ('603301.SZ', 'No data found, symbol may be delisted')

[*********************100%***********************]  57 of 86 downloaded

In [59]:
start_date = pd.to_datetime('1996-09-26',format='%Y-%m-%d')
end_date = pd.to_datetime('1996-10-26',format='%Y-%m-%d')
indicator = [(date>=start_date) & (date<=end_date) for date in data.index]

In [110]:
def func(x):
    x = x.dropna()
    no_eff_obs = [x.shape[0]]
    min_date = [min(x.date)]
    max_date = [max(x.date)]
    sub_df = pd.DataFrame({"no_eff_obs":no_eff_obs,"min_date":min_date,"max_date":max_date})
    return sub_df

In [ ]:
def panel_data_apply(func):
		storage = []
		for ticker in self.ticker_list:
			sub_df = self.panel_data[self.panel_data.ticker==ticker]
			sub_df = func(sub_df)
			storage.append(sub_df)
		df = pd.concat(storage)
		return df

In [74]:
data

           097976867                                 000613.SZ              \
                Open High Low Close Adj Close Volume      Open  High   Low
Date
1996-09-26       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-09-27       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-09-30       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-01       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-02       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-03       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-04       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-07       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-08       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-09       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-10       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-11       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-14       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-15       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-16       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-17       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-18       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-21       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-22       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-23       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-24       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-25       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-28       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-29       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-30       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-10-31       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-11-01       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-11-04       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-11-05       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
1996-11-06       NaN  NaN NaN   NaN       NaN    NaN       NaN   NaN   NaN
...              ...  ...  ..   ...       ...    ...       ...   ...   ...
2019-10-22       NaN  NaN NaN   NaN       NaN    NaN      4.67  4.75  4.66
2019-10-23       NaN  NaN NaN   NaN       NaN    NaN      4.75  4.89  4.71
2019-10-24       NaN  NaN NaN   NaN       NaN    NaN      4.78  4.93  4.70
2019-10-25       NaN  NaN NaN   NaN       NaN    NaN      4.86  5.10  4.84
2019-10-28       NaN  NaN NaN   NaN       NaN    NaN      4.93  4.95  4.83
2019-10-29       NaN  NaN NaN   NaN       NaN    NaN      4.95  4.95  4.76
2019-10-30       NaN  NaN NaN   NaN       NaN    NaN      4.75  4.78  4.70
2019-10-31       NaN  NaN NaN   NaN       NaN    NaN      4.74  4.78  4.64
2019-11-01       NaN  NaN NaN   NaN       NaN    NaN      4.65  4.74  4.62
2019-11-04       NaN  NaN NaN   NaN       NaN    NaN      4.71  4.72  4.67
2019-11-05       NaN  NaN NaN   NaN       NaN    NaN      4.66  4.85  4.63
2019-11-06       NaN  NaN NaN   NaN       NaN    NaN      4.69  4.70  4.63
2019-11-07       NaN  NaN NaN   NaN       NaN    NaN      4.69  4.73  4.65
2019-11-08       NaN  NaN NaN   NaN       NaN    NaN      4.71  5.17  4.70
2019-11-11       NaN  NaN NaN   NaN       NaN    NaN      5.18  5.53  4.88
2019-11-12       NaN  NaN NaN   NaN       NaN    NaN      5.13  5.46  5.01
2019-11-13       NaN  NaN NaN   NaN       NaN    NaN      5.21  5.46  5.18
2019-11-14       NaN  NaN NaN   NaN       NaN    NaN      5.21  5.28  5.04
2019-11-15       NaN  NaN NaN   NaN       NaN    NaN      5.14  5.18  5.02
2019-11-18       NaN  NaN NaN   NaN       NaN    NaN      4.93  5.07  4.93
2019-11-19       NaN  NaN NaN   NaN       NaN    NaN      5.12  5.12  5.02
2019-11-20       NaN  NaN NaN   NaN       NaN    NaN      5.02  5.33  4.96
2019-11-21       NaN  NaN NaN   NaN       NaN    NaN      5.20  5.33  5.18
2019-11-22       NaN  NaN NaN   NaN       NaN    NaN      5.15  5.25  5.03
2019-11-25       NaN  NaN NaN   NaN       NaN    NaN      5.15  5.15  5.03
2019-11-26       NaN  NaN NaN   NaN       NaN    NaN      5.03  5.31  5.01
2019-11-27       NaN  NaN NaN   NaN       NaN    NaN      5.28  5.44  5.21
2019-11-28       NaN  NaN NaN   NaN       NaN    NaN      5.30  5.44  5.22
2019-11-29       NaN  NaN NaN   NaN       NaN    NaN      5.38  5.52  5.28
2019-12-02       NaN  NaN NaN   NaN       NaN    NaN      5.39  5.48  5.28

                                       000612.SZ                          \
           Close Adj Close      Volume      Open    High     Low   Close
Date
1996-09-26   NaN       NaN         NaN    1.4591  1.4801  1.3478  1.3948
1996-09-27   NaN       NaN         NaN    1.3825  1.4220  1.3602  1.4196
1996-09-30   NaN       NaN         NaN    1.3825  1.4220  1.3602  1.4196
1996-10-01   NaN       NaN         NaN    1.3825  1.4220  1.3602  1.4196
1996-10-02   NaN       NaN         NaN    1.3825  1.4220  1.3602  1.4196
1996-10-03   NaN       NaN         NaN    1.4591  1.5395  1.4591  1.5086
1996-10-04   NaN       NaN         NaN    1.5086  1.5395  1.4715  1.5148
1996-10-07   NaN       NaN         NaN    1.5148  1.6013  1.5086  1.5717
1996-10-08   NaN       NaN         NaN    1.5679  1.5803  1.4839  1.5679
1996-10-09   NaN       NaN         NaN    1.5704  1.5729  1.4999  1.5172
1996-10-10   NaN       NaN         NaN    1.5012  1.5407  1.4839  1.5333
1996-10-11   NaN       NaN         NaN    1.5581  1.5655  1.4987  1.5086
1996-10-14   NaN       NaN         NaN    1.5073  1.5704  1.4839  1.5308
1996-10-15   NaN       NaN         NaN    1.5395  1.6075  1.4962  1.6013
1996-10-16   NaN       NaN         NaN    1.6236  1.6805  1.5457  1.6075
1996-10-17   NaN       NaN         NaN    1.6137  1.7930  1.6137  1.7930
1996-10-18   NaN       NaN         NaN    1.8313  1.8672  1.5951  1.6199
1996-10-21   NaN       NaN         NaN    1.6075  1.6693  1.5951  1.6384
1996-10-22   NaN       NaN         NaN    1.6063  1.6063  1.5407  1.5581
1996-10-23   NaN       NaN         NaN    1.5469  1.6446  1.5469  1.6174
1996-10-24   NaN       NaN         NaN    1.6199  1.6397  1.5581  1.5890
1996-10-25   NaN       NaN         NaN    1.5828  1.5890  1.5457  1.5692
1996-10-28   NaN       NaN         NaN    1.5457  1.6261  1.5333  1.6075
1996-10-29   NaN       NaN         NaN    1.6162  1.6780  1.5964  1.6087
1996-10-30   NaN       NaN         NaN    1.6137  1.6693  1.5840  1.6223
1996-10-31   NaN       NaN         NaN    1.6261  1.6570  1.5976  1.6421
1996-11-01   NaN       NaN         NaN    1.5704  1.6137  1.5457  1.5939
1996-11-04   NaN       NaN         NaN    1.5581  1.6384  1.5469  1.5951
1996-11-05   NaN       NaN         NaN    1.6075  1.6199  1.5704  1.5902
1996-11-06   NaN       NaN         NaN    1.5951  1.6075  1.5457  1.5630
...          ...       ...         ...       ...     ...     ...     ...
2019-10-22  4.73      4.73   2317200.0    4.3600  4.3700  4.3300  4.3600
2019-10-23  4.84      4.84   5022577.0    4.3300  4.3600  4.3100  4.3200
2019-10-24  4.93      4.93   6724075.0    4.2900  4.3300  4.2600  4.3100
2019-10-25  4.93      4.93   6840769.0    4.3100  4.3300  4.2400  4.3100
2019-10-28  4.92      4.92   5274890.0    4.3100  4.3800  4.3000  4.3600
2019-10-29  4.77      4.77   3640300.0    4.3700  4.3900  4.3300  4.3500
2019-10-30  4.74      4.74   2905711.0    4.3500  4.3500  4.2300  4.2300
2019-10-31  4.66      4.66   2333300.0    4.2500  4.2500  4.1600  4.1600
2019-11-01  4.71      4.71   2124157.0    4.1400  4.2600  4.1400  4.2100
2019-11-04  4.67      4.67   1812001.0    4.2100  4.2400  4.1600  4.1800
2019-11-05  4.74      4.74   6075925.0    4.2000  4.2300  4.1600  4.2200
2019-11-06  4.67      4.67   3564300.0    4.2200  4.2500  4.1900  4.2000
2019-11-07  4.70      4.70   2523600.0    4.2400  4.2400  4.1500  4.1700
2019-11-08  5.17      5.17   9924050.0    4.1900  4.2100  4.1500  4.1500
2019-11-11  5.20      5.20  34136033.0    4.1400  4.1400  3.9800  3.9900
2019-11-12  5.39      5.39  25772314.0    3.9900  4.0600  3.9100  4.0000
2019-11-13  5.27      5.27  14199569.0    3.9800  4.0100  3.9300  3.9500
2019-11-14  5.23      5.23  13516613.0    3.9400  3.9600  3.9200  3.9500
2019-11-15  5.02      5.02   8909463.0    3.9600  4.0900  3.9400  3.9600
2019-11-18  5.06      5.06   6712900.0    3.9700  4.0500  3.9400  4.0100
2019-11-19  5.05      5.05   7092320.0    4.0000  4.0700  3.9900  4.0500
2019-11-20  5.30      5.30  15580204.0    4.0400  4.1600  4.0200  4.0900
2019-11-21  5.19      5.19  10775689.0    4.0600  4.0900  4.0400  4.0500
2019-11-22  5.12      5.12   7456200.0    4.0500  4.1100  4.0200  4.0500
2019-11-25  5.03      5.03   4528100.0    4.0200  4.2100  4.0200  4.1900
2019-11-26  5.31      5.31  11298843.0    4.1600  4.1900  4.1000  4.1000
2019-11-27  5.27      5.27  12900502.0    4.0800  4.1300  4.0600  4.0800
2019-11-28  5.34      5.34  11013500.0    4.0700  4.1200  4.0400  4.0600
2019-11-29  5.38      5.38  10462000.0    4.0700  4.0800  4.0100  4.0300
2019-12-02  5.33      5.33   9055100.0    4.0400  4.0700  4.0100  4.0300


           Adj Close      Volume
Date
1996-09-26    1.0054  63416141.0
1996-09-27    1.0232  26122756.0
1996-09-30    1.0232         0.0
1996-10-01    1.0232         0.0
1996-10-02    1.0232         0.0
1996-10-03    1.0874  47362558.0
1996-10-04    1.0918  24087248.0
1996-10-07    1.1328  39366093.0
1996-10-08    1.1301  17637834.0
1996-10-09    1.0936  18020351.0
1996-10-10    1.1052  15094460.0
1996-10-11    1.0874  14534837.0
1996-10-14    1.1034  15128426.0
1996-10-15    1.1542  31262879.0
1996-10-16    1.1587  33422119.0
1996-10-17    1.2923  56395781.0
1996-10-18    1.1676  37169653.0
1996-10-21    1.1809  21571370.0
1996-10-22    1.1230  13878978.0
1996-10-23    1.1658  16871183.0
1996-10-24    1.1453   9651882.0
1996-10-25    1.1310  13325016.0
1996-10-28    1.1587  15493151.0
1996-10-29    1.1595  18060786.0
1996-10-30    1.1694  13016899.0
1996-10-31    1.1836  12795315.0
1996-11-01    1.1489   9043737.0
1996-11-04    1.1497   8491392.0
1996-11-05    1.1462   7912360.0
1996-11-06    1.1266   5281646.0
...              ...         ...
2019-10-22    4.3600   2040960.0
2019-10-23    4.3200   2583800.0
2019-10-24    4.3100   2655064.0
2019-10-25    4.3100   3054942.0
2019-10-28    4.3600   4015403.0
2019-10-29    4.3500   3472548.0
2019-10-30    4.2300   4249540.0
2019-10-31    4.1600   3502006.0
2019-11-01    4.2100   3227432.0
2019-11-04    4.1800   3751379.0
2019-11-05    4.2200   3004764.0
2019-11-06    4.2000   2275002.0
2019-11-07    4.1700   3628000.0
2019-11-08    4.1500   2869784.0
2019-11-11    3.9900   4867402.0
2019-11-12    4.0000   2982900.0
2019-11-13    3.9500   2516351.0
2019-11-14    3.9500   3071405.0
2019-11-15    3.9600   4363143.0
2019-11-18    4.0100   3032566.0
2019-11-19    4.0500   3041060.0
2019-11-20    4.0900   5873984.0
2019-11-21    4.0500   3634360.0
2019-11-22    4.0500   4798560.0
2019-11-25    4.1900  10014791.0
2019-11-26    4.1000   5450280.0
2019-11-27    4.0800   3894002.0
2019-11-28    4.0600   3202700.0
2019-11-29    4.0300   2688200.0
2019-12-02    4.0300   1914342.0

[5801 rows x 18 columns]

In [81]:
storage_df = []
storage_series = []
sub_df = data['000613.SZ']
series = sub_df[['Open','Low']]
storage_series.append(series)
sub_df = pd.concat(storage_series,axis=1)
sub_df["ticker"] = '000613.SZ'
storage_df.append(sub_df)
final = pd.concat(storage_df)

In [82]:
final

            Open   Low     ticker
Date
1996-09-26   NaN   NaN  000613.SZ
1996-09-27   NaN   NaN  000613.SZ
1996-09-30   NaN   NaN  000613.SZ
1996-10-01   NaN   NaN  000613.SZ
1996-10-02   NaN   NaN  000613.SZ
1996-10-03   NaN   NaN  000613.SZ
1996-10-04   NaN   NaN  000613.SZ
1996-10-07   NaN   NaN  000613.SZ
1996-10-08   NaN   NaN  000613.SZ
1996-10-09   NaN   NaN  000613.SZ
1996-10-10   NaN   NaN  000613.SZ
1996-10-11   NaN   NaN  000613.SZ
1996-10-14   NaN   NaN  000613.SZ
1996-10-15   NaN   NaN  000613.SZ
1996-10-16   NaN   NaN  000613.SZ
1996-10-17   NaN   NaN  000613.SZ
1996-10-18   NaN   NaN  000613.SZ
1996-10-21   NaN   NaN  000613.SZ
1996-10-22   NaN   NaN  000613.SZ
1996-10-23   NaN   NaN  000613.SZ
1996-10-24   NaN   NaN  000613.SZ
1996-10-25   NaN   NaN  000613.SZ
1996-10-28   NaN   NaN  000613.SZ
1996-10-29   NaN   NaN  000613.SZ
1996-10-30   NaN   NaN  000613.SZ
1996-10-31   NaN   NaN  000613.SZ
1996-11-01   NaN   NaN  000613.SZ
1996-11-04   NaN   NaN  000613.SZ
1996-11-05   NaN   NaN  000613.SZ
1996-11-06   NaN   NaN  000613.SZ
...          ...   ...        ...
2019-10-22  4.67  4.66  000613.SZ
2019-10-23  4.75  4.71  000613.SZ
2019-10-24  4.78  4.70  000613.SZ
2019-10-25  4.86  4.84  000613.SZ
2019-10-28  4.93  4.83  000613.SZ
2019-10-29  4.95  4.76  000613.SZ
2019-10-30  4.75  4.70  000613.SZ
2019-10-31  4.74  4.64  000613.SZ
2019-11-01  4.65  4.62  000613.SZ
2019-11-04  4.71  4.67  000613.SZ
2019-11-05  4.66  4.63  000613.SZ
2019-11-06  4.69  4.63  000613.SZ
2019-11-07  4.69  4.65  000613.SZ
2019-11-08  4.71  4.70  000613.SZ
2019-11-11  5.18  4.88  000613.SZ
2019-11-12  5.13  5.01  000613.SZ
2019-11-13  5.21  5.18  000613.SZ
2019-11-14  5.21  5.04  000613.SZ
2019-11-15  5.14  5.02  000613.SZ
2019-11-18  4.93  4.93  000613.SZ
2019-11-19  5.12  5.02  000613.SZ
2019-11-20  5.02  4.96  000613.SZ
2019-11-21  5.20  5.18  000613.SZ
2019-11-22  5.15  5.03  000613.SZ
2019-11-25  5.15  5.03  000613.SZ
2019-11-26  5.03  5.01  000613.SZ
2019-11-27  5.28  5.21  000613.SZ
2019-11-28  5.30  5.22  000613.SZ
2019-11-29  5.38  5.28  000613.SZ
2019-12-02  5.39  5.28  000613.SZ

[5801 rows x 3 columns]

In [73]:
panel_data_construction(['Open','High','Low'])

KeyError: '000710.SZ'

In [70]:
low = data['000613.SZ']['Low']
open_price = data['000613.SZ']['Open']
close =data['000613.SZ']['Close']

In [71]:
pd.concat([low,open_price,close], axis=1)

             Low  Open  Close
Date
1996-09-26   NaN   NaN    NaN
1996-09-27   NaN   NaN    NaN
1996-09-30   NaN   NaN    NaN
1996-10-01   NaN   NaN    NaN
1996-10-02   NaN   NaN    NaN
1996-10-03   NaN   NaN    NaN
1996-10-04   NaN   NaN    NaN
1996-10-07   NaN   NaN    NaN
1996-10-08   NaN   NaN    NaN
1996-10-09   NaN   NaN    NaN
1996-10-10   NaN   NaN    NaN
1996-10-11   NaN   NaN    NaN
1996-10-14   NaN   NaN    NaN
1996-10-15   NaN   NaN    NaN
1996-10-16   NaN   NaN    NaN
1996-10-17   NaN   NaN    NaN
1996-10-18   NaN   NaN    NaN
1996-10-21   NaN   NaN    NaN
1996-10-22   NaN   NaN    NaN
1996-10-23   NaN   NaN    NaN
1996-10-24   NaN   NaN    NaN
1996-10-25   NaN   NaN    NaN
1996-10-28   NaN   NaN    NaN
1996-10-29   NaN   NaN    NaN
1996-10-30   NaN   NaN    NaN
1996-10-31   NaN   NaN    NaN
1996-11-01   NaN   NaN    NaN
1996-11-04   NaN   NaN    NaN
1996-11-05   NaN   NaN    NaN
1996-11-06   NaN   NaN    NaN
...          ...   ...    ...
2019-10-22  4.66  4.67   4.73
2019-10-23  4.71  4.75   4.84
2019-10-24  4.70  4.78   4.93
2019-10-25  4.84  4.86   4.93
2019-10-28  4.83  4.93   4.92
2019-10-29  4.76  4.95   4.77
2019-10-30  4.70  4.75   4.74
2019-10-31  4.64  4.74   4.66
2019-11-01  4.62  4.65   4.71
2019-11-04  4.67  4.71   4.67
2019-11-05  4.63  4.66   4.74
2019-11-06  4.63  4.69   4.67
2019-11-07  4.65  4.69   4.70
2019-11-08  4.70  4.71   5.17
2019-11-11  4.88  5.18   5.20
2019-11-12  5.01  5.13   5.39
2019-11-13  5.18  5.21   5.27
2019-11-14  5.04  5.21   5.23
2019-11-15  5.02  5.14   5.02
2019-11-18  4.93  4.93   5.06
2019-11-19  5.02  5.12   5.05
2019-11-20  4.96  5.02   5.30
2019-11-21  5.18  5.20   5.19
2019-11-22  5.03  5.15   5.12
2019-11-25  5.03  5.15   5.03
2019-11-26  5.01  5.03   5.31
2019-11-27  5.21  5.28   5.27
2019-11-28  5.22  5.30   5.34
2019-11-29  5.28  5.38   5.38
2019-12-02  5.28  5.39   5.33

[5801 rows x 3 columns]

In [6]:
def get_multiple_data(ticker_list):
#create a list storage to store dataframe
    storage = []
    i=1
#create a for loop to download dataframe
    for ticker in ticker_list:
        print(i)
        i=i+1
        obj = yf.Ticker(ticker)
        df = obj.history (period ='max')
        df['ticker'] = ticker
        storage.append(df)
    final_df = pd.concat(storage)
    final_df['Date'] = final_df.index
    final_df = final_df[['ticker','Date','Close']]
    colnames = ['ticker','date','price']
    final_df.columns = colnames
    return final_df

In [7]:
df = get_multiple_data(ticker_list)

1
2
3
4
5
6
7
8

In [10]:
df

               ticker       date  price
Date
1997-04-22  000710.SZ 1997-04-22   5.11
1997-04-23  000710.SZ 1997-04-23   5.03
1997-04-24  000710.SZ 1997-04-24   4.87
1997-04-25  000710.SZ 1997-04-25   5.14
1997-04-28  000710.SZ 1997-04-28   5.49
1997-04-29  000710.SZ 1997-04-29   5.08
1997-04-30  000710.SZ 1997-04-30   5.05
1997-05-01  000710.SZ 1997-05-01   5.05
1997-05-02  000710.SZ 1997-05-02   5.05
1997-05-05  000710.SZ 1997-05-05   5.02
1997-05-06  000710.SZ 1997-05-06   4.92
1997-05-07  000710.SZ 1997-05-07   5.01
1997-05-08  000710.SZ 1997-05-08   4.68
1997-05-09  000710.SZ 1997-05-09   4.79
1997-05-12  000710.SZ 1997-05-12   4.89
1997-05-13  000710.SZ 1997-05-13   4.76
1997-05-14  000710.SZ 1997-05-14   4.59
1997-05-15  000710.SZ 1997-05-15   4.74
1997-05-16  000710.SZ 1997-05-16   4.27
1997-05-19  000710.SZ 1997-05-19   4.30
1997-05-20  000710.SZ 1997-05-20   4.32
1997-05-21  000710.SZ 1997-05-21   4.06
1997-05-22  000710.SZ 1997-05-22   3.65
1997-05-23  000710.SZ 1997-05-23   3.49
1997-05-26  000710.SZ 1997-05-26   3.45
1997-05-27  000710.SZ 1997-05-27   3.80
1997-05-28  000710.SZ 1997-05-28   3.78
1997-05-29  000710.SZ 1997-05-29   3.75
1997-05-30  000710.SZ 1997-05-30   3.83
1997-06-02  000710.SZ 1997-06-02   3.92
...               ...        ...    ...
2019-10-22  300482.SZ 2019-10-22  52.20
2019-10-23  300482.SZ 2019-10-23  50.16
2019-10-24  300482.SZ 2019-10-24  48.72
2019-10-25  300482.SZ 2019-10-25  49.81
2019-10-28  300482.SZ 2019-10-28  49.93
2019-10-29  300482.SZ 2019-10-29  50.23
2019-10-30  300482.SZ 2019-10-30  49.81
2019-10-31  300482.SZ 2019-10-31  49.56
2019-11-01  300482.SZ 2019-11-01  49.85
2019-11-04  300482.SZ 2019-11-04  51.69
2019-11-05  300482.SZ 2019-11-05  50.19
2019-11-06  300482.SZ 2019-11-06  49.23
2019-11-07  300482.SZ 2019-11-07  49.61
2019-11-08  300482.SZ 2019-11-08  49.65
2019-11-11  300482.SZ 2019-11-11  47.67
2019-11-12  300482.SZ 2019-11-12  48.52
2019-11-13  300482.SZ 2019-11-13  50.22
2019-11-14  300482.SZ 2019-11-14  52.05
2019-11-15  300482.SZ 2019-11-15  51.93
2019-11-18  300482.SZ 2019-11-18  51.69
2019-11-19  300482.SZ 2019-11-19  52.52
2019-11-20  300482.SZ 2019-11-20  53.38
2019-11-21  300482.SZ 2019-11-21  52.86
2019-11-22  300482.SZ 2019-11-22  48.51
2019-11-25  300482.SZ 2019-11-25  47.20
2019-11-26  300482.SZ 2019-11-26  47.66
2019-11-27  300482.SZ 2019-11-27  47.43
2019-11-28  300482.SZ 2019-11-28  48.24
2019-11-29  300482.SZ 2019-11-29  47.74
2019-12-02  300482.SZ 2019-12-02  47.06

[13194 rows x 3 columns]

In [8]:
min(df['date'])

Timestamp('1997-04-22 00:00:00')

In [57]:
storage = []
for ticker in ticker_list:
    sub_df = df[df['ticker']==ticker]
    print(ticker)
    print(sub_df.shape)
    print(min(sub_df.date))
    print(max(sub_df.date))
    if min(sub_df.date)<pd.to_datetime('2005-01-01'):
        storage.append(ticker)

000710.SZ
(5651, 3)
1997-04-22 00:00:00
2019-11-29 00:00:00
['000710.SZ']
300246.SZ
(2034, 3)
2011-07-19 00:00:00
2019-11-29 00:00:00
['000710.SZ']
300404.SZ
(1122, 3)
2015-04-24 00:00:00
2019-11-29 00:00:00
['000710.SZ']
300633.SZ
(647, 3)
2017-04-06 00:00:00
2019-11-29 00:00:00
['000710.SZ']
300298.SZ
(1873, 3)
2012-03-19 00:00:00
2019-11-29 00:00:00
['000710.SZ']
300562.SZ
(740, 3)
2016-11-16 00:00:00
2019-11-29 00:00:00
['000710.SZ']
300685.SZ
(566, 3)
2017-08-02 00:00:00
2019-11-29 00:00:00
['000710.SZ']
300482.SZ
(1077, 3)
2015-06-30 00:00:00
2019-11-29 00:00:00
['000710.SZ']

In [58]:
print(storage)

['000710.SZ']

In [101]:
df.to_csv('Chinese_price.csv',index=False)

In [108]:
df.head()

               ticker       date  price
Date
2019-01-28  300759.SZ 2019-01-28  11.00
2019-01-29  300759.SZ 2019-01-29  12.09
2019-01-30  300759.SZ 2019-01-30  13.30
2019-01-31  300759.SZ 2019-01-31  14.63
2019-02-01  300759.SZ 2019-02-01  16.09

In [111]:
df[df['ticker']=='300759.SZ'].asfreq(freq='BM',method='ffill')

               ticker       date  price
Date
2019-01-31  300759.SZ 2019-01-31  14.63
2019-02-28  300759.SZ 2019-02-28  38.68
2019-03-29  300759.SZ 2019-03-29  42.00
2019-04-30  300759.SZ 2019-04-26  36.29
2019-05-31  300759.SZ 2019-05-31  36.11
2019-06-28  300759.SZ 2019-06-28  34.08
2019-07-31  300759.SZ 2019-07-31  35.55
2019-08-30  300759.SZ 2019-08-30  41.78
2019-09-30  300759.SZ 2019-09-30  46.55
2019-10-31  300759.SZ 2019-10-31  56.02
2019-11-29  300759.SZ 2019-11-29  47.93